### ISSUE TITLE
Watershed delineation tool using lazy loading with zarr and Dask?

### ISSUE THREAD

**Issue by sebastienlanglois** [davidbrochart/flow_acc_3s#1]
Hi @davidbrochart,

I have noticed that you've added a zarr version of the Hydroshed's direction and flow_accumulation at 3 seconds resolution on the pangeo datastore.

Have you been able to use a watershed delineation tool (such as [pysheds](https://github.com/mdbartos/pysheds)) on top of the zarr data?

Most of the watershed delineation tool are limited to process rather small sized DEM/Dir/Flow_acc rasters in memory only which means that these inputs need to be recreated/transformed for every new project.

I feel like there is an opportunity for such tools to use zarr format as input with lazy loading on top of Dask.
Have you ever worked on or seen such tool?

Thanks,

**Comment by davidbrochart** [comment]
Hi Sebastien,

I didn't know about pysheds, thanks for pointing out!
I have this project, that I need to get back to: https://github.com/davidbrochart/pangeo-streamflow
It has watershed delineation using Cython, with data in the pangeo store but in GDAL VRT format. I don't remember having uploaded Hydroshed's flow direction and accumulation in the zarr format, but anyway it wouldn't be hard to do. VRT gives us similar chunking in this case.
I don't think this code works right know but it is definitely on my roadmap, I just need to find some time to work on it. On top of delineation, I have implemented what I call "basin partitioning" (see http://davidbrochart.github.io/streamflow/visualization/2017/01/13/streamflow-visualization.html).
If this is of interest, I could polish the code and make a library out of it.

**Comment by sebastienlanglois** [comment]
I've opened an issue instead in your [pangeo-streamflow](https://github.com/davidbrochart/pangeo-streamflow/issues/1) repository which seems more appropriate and will be closing this one
